# Generated by Django 5.2.1 on 2025-05-19 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backlogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('backlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epics', to='backlogs.backlog')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
