# Generated by Django 5.2.1 on 2025-05-19 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('epics', '0002_initial'),
        ('sprints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('epics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stories', to='epics.epic')),
                ('sprints', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stories', to='sprints.sprint')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
